# Generated by Django 4.1.7 on 2023-05-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academic.course'),
        ),
    ]
