# Generated by Django 4.1.7 on 2023-05-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_rename_name_course_title_course_code_course_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academic.course'),
        ),
        migrations.CreateModel(
            name='BorrowedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.level')),
            ],
        ),
    ]
