# Generated by Django 4.1.7 on 2023-05-30 11:46

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_course_pre_borrowedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('content', froala_editor.fields.FroalaField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.department')),
            ],
        ),
    ]
